/*
 * This source file was generated by the Gradle 'init' task
 */
package com.hibuz.kafka.connect.exmaples.config;

import org.junit.jupiter.api.Test;

import com.hibuz.kafka.connect.examples.config.RandomConnectorConfig;

import static org.junit.jupiter.api.Assertions.assertEquals;

class RandomConnectorConfigTest {
    @Test void testGetMessage() {
        assertEquals("1.0.0", RandomConnectorConfig.CONNECTOR_VERSION);
    }
}
